DO $$
DECLARE
  campanha_id_type text;
  bonificacao_id_generation text;
BEGIN
  SELECT format_type(attribute.atttypid, attribute.atttypmod)
  INTO campanha_id_type
  FROM pg_attribute AS attribute
  WHERE attribute.attrelid = 'public.campanhas_ftw'::regclass
    AND attribute.attname = 'id'
    AND NOT attribute.attisdropped;

  IF campanha_id_type IS NULL THEN
    RAISE EXCEPTION 'Não foi possível encontrar a coluna id de campanhas_ftw';
  END IF;

  CASE campanha_id_type
    WHEN 'uuid' THEN bonificacao_id_generation := 'DEFAULT gen_random_uuid()';
    WHEN 'smallint', 'integer', 'bigint' THEN
      bonificacao_id_generation := 'GENERATED BY DEFAULT AS IDENTITY';
    ELSE
      RAISE EXCEPTION 'Tipo de id não suportado em campanhas_ftw: %', campanha_id_type;
  END CASE;

  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS public.campanhas_ftw_bonificacoes (
      id %s %s PRIMARY KEY,
      campanha_id %s NOT NULL REFERENCES public.campanhas_ftw(id) ON DELETE CASCADE,
      tipo text NOT NULL CHECK (tipo IN (''pares'', ''valor'')),
      percentual_min numeric(6,2) NOT NULL CHECK (percentual_min >= 0),
      percentual_max numeric(6,2),
      valor_bonificacao numeric(12,2) NOT NULL CHECK (valor_bonificacao > 0),
      created_at timestamptz NOT NULL DEFAULT now(),
      CHECK (percentual_max IS NULL OR percentual_max > percentual_min)
    )',
    campanha_id_type,
    bonificacao_id_generation,
    campanha_id_type
  );
END $$;

CREATE INDEX IF NOT EXISTS campanhas_ftw_bonificacoes_campanha_tipo_idx
  ON public.campanhas_ftw_bonificacoes (campanha_id, tipo);

ALTER TABLE public.campanhas_ftw_bonificacoes ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON public.campanhas_ftw_bonificacoes TO authenticated;

DROP POLICY IF EXISTS campanhas_ftw_bonificacoes_select
  ON public.campanhas_ftw_bonificacoes;
CREATE POLICY campanhas_ftw_bonificacoes_select
  ON public.campanhas_ftw_bonificacoes
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS campanhas_ftw_bonificacoes_insert
  ON public.campanhas_ftw_bonificacoes;
CREATE POLICY campanhas_ftw_bonificacoes_insert
  ON public.campanhas_ftw_bonificacoes
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS campanhas_ftw_bonificacoes_update
  ON public.campanhas_ftw_bonificacoes;
CREATE POLICY campanhas_ftw_bonificacoes_update
  ON public.campanhas_ftw_bonificacoes
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS campanhas_ftw_bonificacoes_delete
  ON public.campanhas_ftw_bonificacoes;
CREATE POLICY campanhas_ftw_bonificacoes_delete
  ON public.campanhas_ftw_bonificacoes
  FOR DELETE TO authenticated USING (true);

NOTIFY pgrst, 'reload schema';