DO $$
DECLARE
  campanha_id_type text;
  campanha_id_generation text;
  funcionario_id_type text;
  funcionario_id_generation text;
BEGIN
  SELECT format_type(attribute.atttypid, attribute.atttypmod)
  INTO campanha_id_type
  FROM pg_attribute AS attribute
  WHERE attribute.attrelid = 'public.setores'::regclass
    AND attribute.attname = 'id'
    AND NOT attribute.attisdropped;

  SELECT format_type(attribute.atttypid, attribute.atttypmod)
  INTO funcionario_id_type
  FROM pg_attribute AS attribute
  WHERE attribute.attrelid = 'public.funcionarios'::regclass
    AND attribute.attname = 'id'
    AND NOT attribute.attisdropped;

  IF campanha_id_type IS NULL OR funcionario_id_type IS NULL THEN
    RAISE EXCEPTION 'Não foi possível encontrar as colunas id de setores ou funcionarios';
  END IF;

  CASE campanha_id_type
    WHEN 'uuid' THEN campanha_id_generation := 'DEFAULT gen_random_uuid()';
    WHEN 'smallint', 'integer', 'bigint' THEN
      campanha_id_generation := 'GENERATED BY DEFAULT AS IDENTITY';
    ELSE
      RAISE EXCEPTION 'Tipo de id não suportado em setores: %', campanha_id_type;
  END CASE;

  CASE funcionario_id_type
    WHEN 'uuid' THEN funcionario_id_generation := 'DEFAULT gen_random_uuid()';
    WHEN 'smallint', 'integer', 'bigint' THEN
      funcionario_id_generation := 'GENERATED BY DEFAULT AS IDENTITY';
    ELSE
      RAISE EXCEPTION 'Tipo de id não suportado em funcionarios: %', funcionario_id_type;
  END CASE;

  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS public.campanhas_ftw (
      id %s %s PRIMARY KEY,
      mes text NOT NULL UNIQUE CHECK (mes ~ ''^[0-9]{4}-(0[1-9]|1[0-2])$''),
      meta_pares integer NOT NULL CHECK (meta_pares > 0),
      meta_valor numeric(12,2) NOT NULL CHECK (meta_valor > 0),
      created_at timestamptz NOT NULL DEFAULT now()
    )',
    campanha_id_type,
    campanha_id_generation
  );

  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS public.campanhas_ftw_resultados (
      id %s %s PRIMARY KEY,
      campanha_id %s NOT NULL REFERENCES public.campanhas_ftw(id) ON DELETE CASCADE,
      funcionario_id %s NOT NULL REFERENCES public.funcionarios(id) ON DELETE CASCADE,
      total_pares integer NOT NULL DEFAULT 0,
      total_valor numeric(12,2) NOT NULL DEFAULT 0,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      UNIQUE (campanha_id, funcionario_id)
    )',
    funcionario_id_type,
    funcionario_id_generation,
    campanha_id_type,
    funcionario_id_type
  );
END $$;

ALTER TABLE public.campanhas_ftw ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campanhas_ftw_resultados ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.campanhas_ftw TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.campanhas_ftw_resultados TO authenticated;

DROP POLICY IF EXISTS campanhas_ftw_select ON public.campanhas_ftw;
CREATE POLICY campanhas_ftw_select
  ON public.campanhas_ftw FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS campanhas_ftw_insert ON public.campanhas_ftw;
CREATE POLICY campanhas_ftw_insert
  ON public.campanhas_ftw FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS campanhas_ftw_update ON public.campanhas_ftw;
CREATE POLICY campanhas_ftw_update
  ON public.campanhas_ftw FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS campanhas_ftw_delete ON public.campanhas_ftw;
CREATE POLICY campanhas_ftw_delete
  ON public.campanhas_ftw FOR DELETE TO authenticated USING (true);

DROP POLICY IF EXISTS campanhas_ftw_resultados_select ON public.campanhas_ftw_resultados;
CREATE POLICY campanhas_ftw_resultados_select
  ON public.campanhas_ftw_resultados FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS campanhas_ftw_resultados_insert ON public.campanhas_ftw_resultados;
CREATE POLICY campanhas_ftw_resultados_insert
  ON public.campanhas_ftw_resultados FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS campanhas_ftw_resultados_update ON public.campanhas_ftw_resultados;
CREATE POLICY campanhas_ftw_resultados_update
  ON public.campanhas_ftw_resultados FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS campanhas_ftw_resultados_delete ON public.campanhas_ftw_resultados;
CREATE POLICY campanhas_ftw_resultados_delete
  ON public.campanhas_ftw_resultados FOR DELETE TO authenticated USING (true);

NOTIFY pgrst, 'reload schema';